version: '2.1'

volumes:
  adaptdata:
  adaptdb:

networks:
  tlc:

services:
  mongodb:
    image: mongo:3.6
    container_name: "adaptdb"
    volumes:
    - adaptdb:/data/db
    networks:
      - tlc
    ports:
    - "32017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null

  adapt:
    image: sandyman/adaptlearning:latest
    container_name: "adaptlearning"
    volumes:
    - adaptdata:/adapt_authoring-${AAT_VER}
    networks:
    - tlc
    ports:
    - "5000:5000"
    command: node server
