version: '2'

volumes:
  adaptdata:
    external:
      name: dockeradaptlearning_adaptdata

services:
  install:
    image: sandyman/adaptlearning:latest
    container_name: "adaptlearning"
    volumes:
      - adaptdata:/adapt_authoring
    external_links:
      - adaptdb
    command: node install --install Y --serverPort 5000 --serverName localhost --dbHost adaptdb --dbName adapt-tenant-master --dbPort 27017 --dataRoot data --sessionSecret teYS3w20F7vAg83n47oZ --useffmpeg Y --smtpService dummy --smtpUsername smtpUser --smtpPassword smtpPass --fromAddress you@example.com --name master --displayName Master --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD} # && node upgrade --Y/n Y

  upgrade:
    extends:
      service: install
    command: node upgrade --Y/n Y

